
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        EVENT_ADD_NEW:"EVENT_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        NEWS_ADD_MODAL:"NEWS_ADD_MODAL",
        MODAL_EXCEL_ADD:"MODAL_EXCEL_ADD",
        DEFAULT : "",
        EDIT_LEAD_MODAL:"EDIT_LEAD_MODAL",
        EDIT_EVENT_MODAL:"EDIT_EVENT_MODAL",
        EDIT_NEWS_MODAL:"EDIT_NEWS_MODAL",
        EDIT_ADS_MODAL:"EDIT_ADS_MODAL",

        ADD_ADVERTISMENT:"ADD_ADVERTISMENT"
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
    },
});
